[images]
  remote_images = ["https://img.youtube.com/**", "https://i.ytimg.com/**", "https://yt3.ggpht.com/**"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@node-rs/argon2"]
